### ISSUE TITLE
Installation with Python 3.12 will not work

### ISSUE THREAD

**Issue by bauergeorg** [memory/python-dpkg#17]
When I try to install pydpkg with python 3.12 I get an error (python 3.9 runs without problems):

```shell
PS C:\repository_git\ee-python-hil> pip3.12 install pydpkg
Defaulting to user installation because normal site-packages is not writeable
Collecting pydpkg
  Using cached pydpkg-1.9.2-py3-none-any.whl.metadata (12 kB)
Collecting PGPy==0.6.0 (from pydpkg)
  Using cached PGPy-0.6.0.tar.gz (603 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting arpy<3.0.0,>=2.3.0 (from pydpkg)
  Using cached arpy-2.3.0.tar.gz (9.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cryptography>=39.0.1 in c:\users\bauer\appdata\roaming\python\python312\site-packages (from pydpkg) (42.0.5)
Requirement already satisfied: six<2.0.0,>=1.16.0 in c:\users\bauer\appdata\roaming\python\python312\site-packages (from pydpkg) (1.16.0)
Collecting zstandard<0.20.0,>=0.19.0 (from pydpkg)
  Using cached zstandard-0.19.0.tar.gz (633 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Bauer\AppData\Local\Temp\pip-build-env-nty4zw1f\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Bauer\AppData\Local\Temp\pip-build-env-nty4zw1f\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Bauer\AppData\Local\Temp\pip-build-env-nty4zw1f\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Bauer\AppData\Local\Temp\pip-build-env-nty4zw1f\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 90, in <module>
        File "C:\Users\Bauer\AppData\Local\Temp\pip-install-ux9b_mfl\zstandard_8d647cd7b1f04ad2a1122ac453714bd3\setup_zstd.py", line 66, in get_c_extension
          compiler.initialize()
        File "C:\Users\Bauer\AppData\Local\Temp\pip-build-env-nty4zw1f\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Bauer\AppData\Local\Temp\pip-build-env-nty4zw1f\overlay\Lib\site-packages\setuptools\msvc.py", line 228, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Bauer\AppData\Local\Temp\pip-build-env-nty4zw1f\overlay\Lib\site-packages\setuptools\msvc.py", line 185, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Here some system information:
```
PS C:\repository_git\ee-python-hil> python -V    
Python 3.12.2
PS C:\repository_git\ee-python-hil> pip3.12 -V
pip 24.0 from C:\Program Files\Python312\Lib\site-packages\pip (python 3.12)
PS C:\repository_git\ee-python-hil> systeminfo
Betriebssystemname:                            Microsoft Windows 11 Pro
Betriebssystemversion:                         10.0.22631 Nicht zutreffend Build 22631
Hotfix(es):                                    5 Hotfix(e) installiert.
                                               [01]: KB5034467
                                               [02]: KB5012170
                                               [03]: KB5027397
                                               [04]: KB5034765
                                               [05]: KB5034225
```

@memory don't hesitate to contact me to get more information if you need. First of all I would try to update [zstandard](https://pypi.org/project/zstandard/) a new version 0.22.0 released at november last year. Thanks a lot!

**Comment by memory** [comment]
Hi @bauergeorg thank you for the report! I'm currently traveling so it may be a day or two until I'm able to attend to this, but I'll try to get it sorted ASAP.

**Comment by memory** [comment]
@bauergeorg sorry for the delay, but version 1.9.3 is now available on pypi and should run successfully on python 3.11 and 3.12.  Please reopen this issue if you run into any difficulties.
