### ISSUE TITLE
module 'cryptography.utils' has no attribute 'register_interface'

### ISSUE THREAD

**Issue by bauergeorg** [memory/python-dpkg#8]
Newest Version of pydpkg and cryptography throws an error:

```
>>> import pydpkg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/pydpkg/__init__.py", line 6, in <module>
    from pydpkg import dsc
  File "/usr/local/lib/python3.9/dist-packages/pydpkg/dsc.py", line 10, in <module>
    import pgpy
  File "/usr/local/lib/python3.9/dist-packages/pgpy/__init__.py", line 4, in <module>
    from .pgp import PGPKey
  File "/usr/local/lib/python3.9/dist-packages/pgpy/pgp.py", line 27, in <module>
    from .constants import CompressionAlgorithm
  File "/usr/local/lib/python3.9/dist-packages/pgpy/constants.py", line 23, in <module>
    from ._curves import BrainpoolP256R1, BrainpoolP384R1, BrainpoolP512R1, X25519, Ed25519
  File "/usr/local/lib/python3.9/dist-packages/pgpy/_curves.py", line 37, in <module>
    @utils.register_interface(ec.EllipticCurve)
AttributeError: module 'cryptography.utils' has no attribute 'register_interface'
```

Here is the extract of pip list:
```
# pip list
Package          Version
---------------- --------------
arpy             2.3.0
attrs            22.1.0
bcrypt           4.0.0
certifi          2020.6.20
cffi             1.15.1
chardet          4.0.0
cryptography     38.0.1
ftd2xx           1.3.1
httplib2         0.18.1
idna             2.10
iniconfig        1.1.1
numpy            1.23.2
packaging        21.3
paramiko         2.11.0
PGPy             0.5.4
pip              20.3.4
pluggy           1.0.0
py               1.11.0
pyasn1           0.4.8
pycparser        2.21
pycurl           7.43.0.6
pydpkg           1.7.0
pyftdi           0.54.0
PyNaCl           1.5.0
pyparsing        3.0.9
pyserial         3.5
PySimpleSOAP     1.16.2
pytest           7.1.3
python-apt       2.2.1
python-debian    0.1.39
python-debianbts 3.1.0
pyusb            1.2.1
reportbug        7.10.3+deb11u1
requests         2.25.1
setuptools       52.0.0
six              1.16.0
tomli            2.0.1
urllib3          1.26.5
wheel            0.34.2
zstandard        0.18.0
```

**Comment by n-oden** [comment]
Thank you for the heads up. I'll try to get a new release out today or tomorrow.

**Comment by memory** [comment]
oof, it looks like the problem is actually upstream with the pgpy library: https://github.com/SecurityInnovation/PGPy/issues/402

For now it looks like the only reasonable solution is to manually pin back the dependency on pycrypto to 37.0.4, which I guess we'll have to do

**Comment by memory** [comment]
v1.8.0, just released, should address this. Please re-open if it does not!

**Comment by bauergeorg** [comment]
Thanks a lot for your greatful **fast** work! It works fine.
